name: Go

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    strategy:
      matrix:
        go: ['1.19', '1.20']

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.41
          # handled by actions/setup-go
          skip-cache: true

  test:
    strategy:
      matrix:
        go: ['1.19', '1.20']

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        run: go test -v ./...
